#!/bin/bash
#$ -pe smp 12
#$ -q largemem
#$ -N rnaseq_test
#$ -o job_logs/
#$ -e job_logs/
#$ -M nvincen2@nd.edu
#$ -m abe


# module load bio/nf-core
conda activate nfcore-env

pipeline="/temp180/mpfrende/nvincen2/NicloTemp/02_mapping/mapping_scripts/nf-core-rnaseq_3.21.0/3_21_0/"

# Set the Singularity cache directory
export NXF_SINGULARITY_CACHEDIR=/users/nvincen2/.singularity

# Run the pipeline
nextflow run $pipeline \
-profile test,singularity \
--outdir ../test_outputs/
