#!/bin/bash
#$ -q largemem
#$ -pe smp 8
#$ -M nvincen2@nd.edu
#$ -m abe
#$ -N hisat2_build_combined
#$ -o job_logs/
#$ -e job_logs/

module load bio/0724

ORG="combined"

mkdir -p ../hisat2-build_indeces/${ORG}_index

cd ../../Data/reference_data/Combined/

hisat2_extract_splice_sites.py ${ORG}_genomic.gtf > ${ORG}.ss
hisat2_extract_exons.py ${ORG}_genomic.gtf > ${ORG}.exon
hisat2-build -p $NSLOTS --ss ${ORG}.ss --exon ${ORG}.exon \
	combined_genomic.fna \
	/temp180/mpfrende/nvincen2/NicloTemp/02_mapping/hisat2-build_indeces/${ORG}_index/${ORG}_index
