#!/bin/bash
#$ -q largemem
#$ -pe smp 4
#$ -t 1-36
#$ -tc 12
#$ -N hisat2_sam_all_Btru
#$ -o job_logs/
#$ -e job_logs/

module load bio/0724

ORG="Btru"

INDEX="/temp180/mpfrende/nvincen2/NicloTemp/02_mapping/hisat2-build_indeces/${ORG}_index/${ORG}_index"
SAMP_DIR="/temp180/mpfrende/nvincen2/NicloTemp/01_QC/trimmed/combined_lanes"

# Make a sorted array of all R1 fastq files
r1_files=( $(ls ${SAMP_DIR}/*_R1_combined.fastq.gz | sort) )

# Access the R1 file for this array task
R1="${r1_files[$SGE_TASK_ID-1]}"

# Extract sample name from filename
# Extract basename without path and remove extensions
f=$(basename "$R1")
base="${f%_R1_combined.fastq.gz}"

SAMP_NAME=$base

OUTDIR="/temp180/mpfrende/nvincen2/NicloTemp/02_mapping/hisat2_sambam_out/stranded/${ORG}_only/${SAMP_NAME}"

mkdir -p ${OUTDIR}

hisat2 -p 4 --rna-strandness RF --dta -x ${INDEX} \
  -1 ${SAMP_DIR}/${SAMP_NAME}_R1_combined.fastq.gz -2 ${SAMP_DIR}/${SAMP_NAME}_R2_combined.fastq.gz 2> \
${OUTDIR}/${SAMP_NAME}.${ORG}.hisat2.log \
  | samtools view -bS - \
  | samtools sort -o ${OUTDIR}/${SAMP_NAME}.${ORG}.sorted.bam
samtools index ${OUTDIR}/${SAMP_NAME}.${ORG}.sorted.bam
samtools flagstat ${OUTDIR}/${SAMP_NAME}.${ORG}.sorted.bam > ${OUTDIR}/${SAMP_NAME}.${ORG}.flagstat.txt
