#!/bin/bash
#$ -pe smp 4
#$ -q largemem
#$ -N rnaseq_real_job
#$ -o job_logs/
#$ -e job_logs/

# Inputs
samplesheet="/temp180/mpfrende/nvincen2/NicloTemp/01_QC/trimmed/combined_lanes/samplesheet.csv"
genome="/temp180/mpfrende/nvincen2/NicloTemp/Data/reference_data/Combined/combined_genomic.fna"
gtf="/temp180/mpfrende/nvincen2/NicloTemp/Data/reference_data/Combined/combined_genomic.gtf"
outdir="/temp180/mpfrende/nvincen2/NicloTemp/02_mapping/nfcore_output"
email="nvincen2@nd.edu"

# Load the nf-core software module
module load bio/nf-core

# Set the Singularity cache directory
export NXF_SINGULARITY_CACHEDIR=/software/n/nf-core/3.3.1/singularity

# Run the nf-core/rnaseq pipeline
nextflow run nf-core/rnaseq -r 3.19.0 \
    -profile singularity \
    --input $samplesheet \
    --fasta $genome \
    --gtf $gtf \
    --outdir $outdir \
    --email $email
