# names/email
email: "nmcadam2@nd.edu"
multiqc_title: "CURE_Superbugs_remapped"

# input/output
input: "/scratch365/nmcadam2/superBugs_WD/nfCore/samplesheet.csv"
outdir: "/scratch365/nmcadam2/superBugs_WD/nfCore/outputs/withTranscripts"

# Genome references
fasta: "/scratch365/nmcadam2/superBugs_WD/nfCore/refs/Abaumannii_refSeq_genomic.fna"
gtf: "/scratch365/nmcadam2/superBugs_WD/nfCore/refs/clean.fixed.gtf"

# Other parameters
skip_rseqc: true
aligner: "star_salmon"
pseudo_aligner: "salmon"
deseq2_vst: true
trimmer: "fastp"
extra_fastp_args: "--trim_poly_x"
extra_salmon_quant_args: "--noLengthCorrection"
extra_star_align_args: "--alignIntronMax 1 --alignIntronMin 2 --alignEndsType EndToEnd --quantMode TranscriptomeSAM"
# Counting level
featurecounts_feature_type: "CDS"
featurecounts_group_type: "locus_tag"

